export enum ConfigCheckResult {
    NOT_INITIALIZED = 'NOT_INITIALIZED',
    REQUIRED = 'REQUIRED',
    LOCALE_RULES_PATTERN_EMPTY = 'LOCALE_RULES_PATTERN_EMPTY',
    LOCALE_RULES_PATTERN_INVALID_CHARS = 'LOCALE_RULES_PATTERN_INVALID_CHARS',
    LOCALE_RULES_PATTERN_UNSUPPORTED_GLOB = 'LOCALE_RULES_PATTERN_UNSUPPORTED_GLOB',
    LOCALE_RULES_PATTERN_INVALID_DOUBLE_STAR = 'LOCALE_RULES_PATTERN_INVALID_DOUBLE_STAR',
    LOCALE_RULES_PATTERN_PURE_WILDCARD = 'LOCALE_RULES_PATTERN_PURE_WILDCARD',
    CUSTOM_RULE_NOT_DEFINED = 'CUSTOM_RULE_NOT_DEFINED',
}
