export enum TsParserCheckResult {
    INCORRECT_EXPORT_DEFAULT = 'INCORRECT_EXPORT_DEFAULT',
    SPREAD_NOT_IDENTIFIER = 'SPREAD_NOT_IDENTIFIER',
    SPREAD_VARIABLE_NOT_FOUND = 'SPREAD_VARIABLE_NOT_FOUND',
    UNSUPPORTED_KEY_TYPE = 'UNSUPPORTED_KEY_TYPE',
    UNSUPPORTED_VALUE_TYPE = 'UNSUPPORTED_VALUE_TYPE',
    UNSUPPORTED_ARRAY_ELEMENT = 'UNSUPPORTED_ARRAY_ELEMENT',
    UNSUPPORTED_OBJECT_PROPERTY = 'UNSUPPORTED_OBJECT_PROPERTY',
    REAPET_KEY = 'REAPET_KEY',
    REAPET_VARIABLE_NAME = 'REAPET_VARIABLE_NAME',
}
